[main]
file_path = "default.xex"
out_directory_path = "ppc"
switch_table_file_path = "jumpTables.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x82F52130
savegprlr_14_address = 0x82F520E0
restfpr_14_address = 0x82F530AC
savefpr_14_address = 0x82F53060
restvmx_14_address = 0x82F570F8
savevmx_14_address = 0x82F56E60
restvmx_64_address = 0x82F5718C
savevmx_64_address = 0x82F56EF4

functions = []

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
    { data = 0x831B1C90, size = 8 }, # C++ Frame Handler
    { data = 0x8324B3BC, size = 8 }, # C Specific Frame Handler
    { data = 0x831C8B50, size = 8 },
    { data = 0x00485645, size = 1972 } # End of .text
]
